apiVersion: v1
kind: Service
metadata:
  name: cvat-frontend-service
  namespace: cvat
  labels:
    app: cvat-app
    tier: frontend
spec:
  type: ClusterIP
  selector:
      app: cvat-app
      tier: frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
